// @generated by scripts/generate-operations.mjs — DO NOT EDIT BY HAND
// source: contracts/desktop-operations.json
// content-hash: 79b0f89db58d0bc1
// regenerate: npm run contracts:generate

//! Desktop cloud_transport operation allowlist (generated).
//!
//! - Fixed origin is enforced by the transport layer (`https://app.itops.sh`).
//! - Authorization is injected only in Rust; never accept it from WebView.
//! - `fixed_body_fields` (e.g. desktop redirect URI) are native-owned constants.
//! - `body_fields` / path / query describe the **HTTP wire schema**, not automatic
//!   WebView inputs. For `Invocation::NativeOnly` (auth.config / auth.exchange),
//!   dynamic fields such as PKCE `code`/`codeVerifier` are Rust-owned only.
//! - `is_ipc_callable` is true only for `Invocation::IpcViaRust`.
//! - No arbitrary URL fields; path templates only.
//! - Operations with `Availability::BlockedPendingTenantIsolation` are
//!   fail-closed: present in the contract catalog but not callable.

#![allow(dead_code)]

/// HTTP method for an allowlisted operation (idiomatic PascalCase variants).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    Get,
    Post,
    Put,
    Patch,
    Delete,
}

impl Method {
    pub fn as_str(self) -> &'static str {
        match self {
            Method::Get => "GET",
            Method::Post => "POST",
            Method::Put => "PUT",
            Method::Patch => "PATCH",
            Method::Delete => "DELETE",
        }
    }
}

/// Whether the desktop client may invoke this operation today (backend readiness).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Availability {
    /// Safe to call under current backend isolation guarantees.
    Available,
    /// Catalogued for v1 coverage but blocked: backend route is not tenant-isolated.
    BlockedPendingTenantIsolation,
}

/// Who may *initiate* this cloud operation on the desktop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Invocation {
    /// Rust-only (e.g. auth_begin_logto / deep-link exchange). Never IPC-callable.
    NativeOnly,
    /// WebView may request via named business IPC; Rust still builds HTTP + injects auth.
    IpcViaRust,
}

/// Allowlisted desktop cloud operations (exhaustive).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Operation {
    AccountTelegramBindStart,
    AccountTelegramBindStatus,
    AccountTelegramUnbind,
    AuthConfig,
    AuthExchange,
    AuthMe,
    MonitoringApplicationsGet,
    MonitoringApplicationsList,
    MonitoringFoundationGet,
    MonitoringFoundationList,
    MonitoringPatrolRecordsGet,
    MonitoringPatrolRecordsList,
    MonitoringPatrolRoundsGet,
    MonitoringPatrolRoundsList,
    MonitoringPatrolTasksGet,
    MonitoringPatrolTasksList,
    ProblemsGetConvergenceTimeline,
    ProblemsList,
    RemediationGet,
    RemediationList,
    ServersGet,
    ServersList,
    SubscriptionAiGet,
    SubscriptionEntitlementsCurrent,
}

/// Every known operation (for exhaustive iteration in transport/tests).
pub const ALL_OPERATIONS: &[Operation] = &[
    Operation::AccountTelegramBindStart,
    Operation::AccountTelegramBindStatus,
    Operation::AccountTelegramUnbind,
    Operation::AuthConfig,
    Operation::AuthExchange,
    Operation::AuthMe,
    Operation::MonitoringApplicationsGet,
    Operation::MonitoringApplicationsList,
    Operation::MonitoringFoundationGet,
    Operation::MonitoringFoundationList,
    Operation::MonitoringPatrolRecordsGet,
    Operation::MonitoringPatrolRecordsList,
    Operation::MonitoringPatrolRoundsGet,
    Operation::MonitoringPatrolRoundsList,
    Operation::MonitoringPatrolTasksGet,
    Operation::MonitoringPatrolTasksList,
    Operation::ProblemsGetConvergenceTimeline,
    Operation::ProblemsList,
    Operation::RemediationGet,
    Operation::RemediationList,
    Operation::ServersGet,
    Operation::ServersList,
    Operation::SubscriptionAiGet,
    Operation::SubscriptionEntitlementsCurrent,
];

/// Static specification for one operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OperationSpec {
    pub id: &'static str,
    pub method: Method,
    pub path: &'static str,
    pub authenticated: bool,
    /// HTTP path placeholder names (wire schema).
    pub path_params: &'static [&'static str],
    /// HTTP query allowlist (wire schema).
    pub query_fields: &'static [&'static str],
    /// HTTP body field names (wire schema). For NativeOnly ops these are Rust-owned.
    pub body_fields: &'static [&'static str],
    /// Native-owned body pairs merged by Rust (never WebView/IPC-controlled).
    pub fixed_body_fields: &'static [(&'static str, &'static str)],
    pub availability: Availability,
    pub invocation: Invocation,
}

/// Fixed HTTPS origin for all desktop cloud calls.
pub const BASE_ORIGIN: &str = "https://app.itops.sh";

/// Fixed WSS origin (reserved for later transport tasks).
pub const WS_ORIGIN: &str = "wss://app.itops.sh";

/// Exact desktop OAuth redirect URI owned by native code (not WebView).
pub const DESKTOP_REDIRECT_URI: &str = "https://app.itops.sh/login/desktop/callback";

/// Content hash of the generating operations JSON (truncated).
pub const OPERATIONS_CONTENT_HASH: &str = "79b0f89db58d0bc1";

/// Resolve the static spec for an operation.
pub fn spec(op: Operation) -> OperationSpec {
    match op {
        Operation::AccountTelegramBindStart => OperationSpec {
            id: "account.telegram.bindStart",
            method: Method::Post,
            path: "/api/auth/me/telegram/bind",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::AccountTelegramBindStatus => OperationSpec {
            id: "account.telegram.bindStatus",
            method: Method::Get,
            path: "/api/auth/me/telegram/bind/{sessionId}",
            authenticated: true,
            path_params: &["sessionId"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::AccountTelegramUnbind => OperationSpec {
            id: "account.telegram.unbind",
            method: Method::Delete,
            path: "/api/auth/me/telegram",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &["current_password"],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::AuthConfig => OperationSpec {
            id: "auth.config",
            method: Method::Get,
            path: "/api/auth/logto/config",
            authenticated: false,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::NativeOnly,
        },
        Operation::AuthExchange => OperationSpec {
            id: "auth.exchange",
            method: Method::Post,
            path: "/api/auth/logto/exchange",
            authenticated: false,
            path_params: &[],
            query_fields: &[],
            body_fields: &["code", "codeVerifier"],
            fixed_body_fields: &[("redirectUri", "https://app.itops.sh/login/desktop/callback")],
            availability: Availability::Available,
            invocation: Invocation::NativeOnly,
        },
        Operation::AuthMe => OperationSpec {
            id: "auth.me",
            method: Method::Get,
            path: "/api/auth/me",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringApplicationsGet => OperationSpec {
            id: "monitoring.applications.get",
            method: Method::Get,
            path: "/api/monitoring/applications/{id}",
            authenticated: true,
            path_params: &["id"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringApplicationsList => OperationSpec {
            id: "monitoring.applications.list",
            method: Method::Get,
            path: "/api/monitoring/applications",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringFoundationGet => OperationSpec {
            id: "monitoring.foundation.get",
            method: Method::Get,
            path: "/api/monitoring/foundation/{id}",
            authenticated: true,
            path_params: &["id"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringFoundationList => OperationSpec {
            id: "monitoring.foundation.list",
            method: Method::Get,
            path: "/api/monitoring/foundation",
            authenticated: true,
            path_params: &[],
            query_fields: &["category"],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringPatrolRecordsGet => OperationSpec {
            id: "monitoring.patrolRecords.get",
            method: Method::Get,
            path: "/api/monitoring/patrol-records/{recordId}",
            authenticated: true,
            path_params: &["recordId"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringPatrolRecordsList => OperationSpec {
            id: "monitoring.patrolRecords.list",
            method: Method::Get,
            path: "/api/monitoring/patrol-records",
            authenticated: true,
            path_params: &[],
            query_fields: &["task_id", "server_group_name", "server_id", "verdict", "limit", "offset"],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringPatrolRoundsGet => OperationSpec {
            id: "monitoring.patrolRounds.get",
            method: Method::Get,
            path: "/api/monitoring/patrol-rounds/{roundId}",
            authenticated: true,
            path_params: &["roundId"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringPatrolRoundsList => OperationSpec {
            id: "monitoring.patrolRounds.list",
            method: Method::Get,
            path: "/api/monitoring/patrol-rounds",
            authenticated: true,
            path_params: &[],
            query_fields: &["task_id", "limit"],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringPatrolTasksGet => OperationSpec {
            id: "monitoring.patrolTasks.get",
            method: Method::Get,
            path: "/api/monitoring/patrol-tasks/{taskId}",
            authenticated: true,
            path_params: &["taskId"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::MonitoringPatrolTasksList => OperationSpec {
            id: "monitoring.patrolTasks.list",
            method: Method::Get,
            path: "/api/monitoring/patrol-tasks",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::ProblemsGetConvergenceTimeline => OperationSpec {
            id: "problems.getConvergenceTimeline",
            method: Method::Get,
            path: "/api/problems/{eventId}/convergence-timeline",
            authenticated: true,
            path_params: &["eventId"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::ProblemsList => OperationSpec {
            id: "problems.list",
            method: Method::Get,
            path: "/api/problems",
            authenticated: true,
            path_params: &[],
            query_fields: &["server_id", "server_name", "server_ip", "root_cause_signature", "problem_state", "binding_title", "event_id", "filter_preset", "page", "page_size"],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::RemediationGet => OperationSpec {
            id: "remediation.get",
            method: Method::Get,
            path: "/api/oncall/remediation-queue/{id}",
            authenticated: true,
            path_params: &["id"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::RemediationList => OperationSpec {
            id: "remediation.list",
            method: Method::Get,
            path: "/api/oncall/remediation-queue",
            authenticated: true,
            path_params: &[],
            query_fields: &["exit_status", "page", "page_size"],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::ServersGet => OperationSpec {
            id: "servers.get",
            method: Method::Get,
            path: "/api/servers/{id}",
            authenticated: true,
            path_params: &["id"],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::ServersList => OperationSpec {
            id: "servers.list",
            method: Method::Get,
            path: "/api/servers",
            authenticated: true,
            path_params: &[],
            query_fields: &["page", "page_size", "name", "ip", "ssh_user", "description", "group_name", "q", "sort", "host_key_status"],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::SubscriptionAiGet => OperationSpec {
            id: "subscription.ai.get",
            method: Method::Get,
            path: "/api/subscription/ai",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
        Operation::SubscriptionEntitlementsCurrent => OperationSpec {
            id: "subscription.entitlements.current",
            method: Method::Get,
            path: "/api/entitlements/current",
            authenticated: true,
            path_params: &[],
            query_fields: &[],
            body_fields: &[],
            fixed_body_fields: &[],
            availability: Availability::Available,
            invocation: Invocation::IpcViaRust,
        },
    }
}

/// True only when availability is Available (blocked ops are fail-closed).
pub fn is_callable(op: Operation) -> bool {
    matches!(spec(op).availability, Availability::Available)
}

/// True only when WebView/business IPC may request this operation.
/// Native-only ops (auth.config / auth.exchange) always return false.
pub fn is_ipc_callable(op: Operation) -> bool {
    matches!(spec(op).invocation, Invocation::IpcViaRust) && is_callable(op)
}

/// Parse operation id string into the enum (unknown → None).
pub fn from_id(id: &str) -> Option<Operation> {
    match id {
            "account.telegram.bindStart" => Some(Operation::AccountTelegramBindStart),
            "account.telegram.bindStatus" => Some(Operation::AccountTelegramBindStatus),
            "account.telegram.unbind" => Some(Operation::AccountTelegramUnbind),
            "auth.config" => Some(Operation::AuthConfig),
            "auth.exchange" => Some(Operation::AuthExchange),
            "auth.me" => Some(Operation::AuthMe),
            "monitoring.applications.get" => Some(Operation::MonitoringApplicationsGet),
            "monitoring.applications.list" => Some(Operation::MonitoringApplicationsList),
            "monitoring.foundation.get" => Some(Operation::MonitoringFoundationGet),
            "monitoring.foundation.list" => Some(Operation::MonitoringFoundationList),
            "monitoring.patrolRecords.get" => Some(Operation::MonitoringPatrolRecordsGet),
            "monitoring.patrolRecords.list" => Some(Operation::MonitoringPatrolRecordsList),
            "monitoring.patrolRounds.get" => Some(Operation::MonitoringPatrolRoundsGet),
            "monitoring.patrolRounds.list" => Some(Operation::MonitoringPatrolRoundsList),
            "monitoring.patrolTasks.get" => Some(Operation::MonitoringPatrolTasksGet),
            "monitoring.patrolTasks.list" => Some(Operation::MonitoringPatrolTasksList),
            "problems.getConvergenceTimeline" => Some(Operation::ProblemsGetConvergenceTimeline),
            "problems.list" => Some(Operation::ProblemsList),
            "remediation.get" => Some(Operation::RemediationGet),
            "remediation.list" => Some(Operation::RemediationList),
            "servers.get" => Some(Operation::ServersGet),
            "servers.list" => Some(Operation::ServersList),
            "subscription.ai.get" => Some(Operation::SubscriptionAiGet),
            "subscription.entitlements.current" => Some(Operation::SubscriptionEntitlementsCurrent),
            _ => None,
    }
}

#[cfg(test)]
mod operations_tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn base_origin_and_redirect_are_pinned() {
        assert_eq!(BASE_ORIGIN, "https://app.itops.sh");
        assert_eq!(WS_ORIGIN, "wss://app.itops.sh");
        assert_eq!(
            DESKTOP_REDIRECT_URI,
            "https://app.itops.sh/login/desktop/callback"
        );
    }

    #[test]
    fn all_operations_round_trip_and_have_allowlists() {
        assert_eq!(ALL_OPERATIONS.len(), 24);
        let mut seen = HashSet::new();
        for &op in ALL_OPERATIONS {
            let s = spec(op);
            assert!(seen.insert(s.id), "duplicate id {}", s.id);
            assert_eq!(from_id(s.id), Some(op));
            assert!(!s.path.is_empty());
            assert!(s.path.starts_with("/api/"));
            // path_params must match placeholders exactly
            let mut placeholders: Vec<&str> = s
                .path
                .split('{')
                .skip(1)
                .filter_map(|chunk| chunk.split('}').next())
                .collect();
            placeholders.sort();
            let mut declared = s.path_params.to_vec();
            declared.sort();
            assert_eq!(declared, placeholders, "path params for {}", s.id);
            // method string is uppercase HTTP
            assert!(matches!(
                s.method.as_str(),
                "GET" | "POST" | "PUT" | "PATCH" | "DELETE"
            ));
        }
        assert_eq!(from_id("not.a.real.op"), None);
    }

    #[test]
    fn auth_exchange_native_owns_pkce_and_redirect() {
        let s = spec(Operation::AuthExchange);
        assert_eq!(s.method, Method::Post);
        assert_eq!(s.path, "/api/auth/logto/exchange");
        assert!(!s.authenticated);
        // Wire schema lists code/codeVerifier; they are Rust-owned, not IPC inputs.
        assert_eq!(s.body_fields, &["code", "codeVerifier"]);
        assert!(!s.body_fields.contains(&"redirectUri"));
        assert_eq!(
            s.fixed_body_fields,
            &[("redirectUri", DESKTOP_REDIRECT_URI)]
        );
        assert_eq!(s.invocation, Invocation::NativeOnly);
        assert!(is_callable(Operation::AuthExchange));
        assert!(
            !is_ipc_callable(Operation::AuthExchange),
            "auth.exchange must not be IPC-callable"
        );
    }

    #[test]
    fn auth_config_is_public_get_native_only() {
        let s = spec(Operation::AuthConfig);
        assert_eq!(s.method, Method::Get);
        assert_eq!(s.path, "/api/auth/logto/config");
        assert!(!s.authenticated);
        assert_eq!(s.invocation, Invocation::NativeOnly);
        assert!(is_callable(Operation::AuthConfig));
        assert!(!is_ipc_callable(Operation::AuthConfig));
    }

    #[test]
    fn native_only_ops_are_rejected_by_ipc_callable_helper() {
        for &op in ALL_OPERATIONS {
            let s = spec(op);
            match s.invocation {
                Invocation::NativeOnly => {
                    assert!(
                        !is_ipc_callable(op),
                        "{} is native_only and must not be IPC-callable",
                        s.id
                    );
                }
                Invocation::IpcViaRust => {
                    if is_callable(op) {
                        assert!(
                            is_ipc_callable(op),
                            "{} is ipc_via_rust + available => IPC-callable",
                            s.id
                        );
                    }
                    // IPC path must not accept PKCE / redirect / token fields.
                    for field in s
                        .path_params
                        .iter()
                        .chain(s.query_fields.iter())
                        .chain(s.body_fields.iter())
                    {
                        let lower = field.to_ascii_lowercase();
                        assert_ne!(lower, "code");
                        assert_ne!(lower, "codeverifier");
                        assert_ne!(lower, "code_verifier");
                        assert_ne!(lower, "redirecturi");
                        assert_ne!(lower, "redirect_uri");
                        assert_ne!(lower, "authorization");
                        assert_ne!(lower, "access_token");
                        assert_ne!(lower, "refresh_token");
                        assert_ne!(lower, "session_token");
                        assert_ne!(lower, "url");
                        assert_ne!(lower, "uri");
                    }
                }
            }
        }
        assert_eq!(spec(Operation::AuthMe).invocation, Invocation::IpcViaRust);
        assert!(is_ipc_callable(Operation::AuthMe));
    }

    #[test]
    fn availability_fail_closed_semantics() {
        // v1 may have zero blocked ops (patrol is tenant-isolated via RLS).
        // Still verify Available => callable and Blocked => not callable.
        let mut available = 0usize;
        let mut blocked = 0usize;
        for &op in ALL_OPERATIONS {
            let s = spec(op);
            match s.availability {
                Availability::Available => {
                    available += 1;
                    assert!(is_callable(op), "{} should be callable", s.id);
                }
                Availability::BlockedPendingTenantIsolation => {
                    blocked += 1;
                    assert!(!is_callable(op), "{} must not be callable", s.id);
                }
            }
        }
        assert!(available >= 1, "expected at least one available op");
        // Zero blocked ops is valid for current v1 catalog.
        let _ = blocked;
        // Enum variant remains for future fail-closed entries.
        let _keep: Availability = Availability::BlockedPendingTenantIsolation;
        assert!(!matches!(
            Availability::BlockedPendingTenantIsolation,
            Availability::Available
        ));
    }

    #[test]
    fn patrol_ops_are_callable() {
        for id in [
            "monitoring.patrolTasks.list",
            "monitoring.patrolTasks.get",
            "monitoring.patrolRecords.list",
            "monitoring.patrolRecords.get",
            "monitoring.patrolRounds.list",
            "monitoring.patrolRounds.get",
        ] {
            let op = from_id(id).expect(id);
            assert!(is_callable(op), "{id} must be callable under tenant RLS");
            assert_eq!(spec(op).availability, Availability::Available);
        }
    }

    #[test]
    fn no_operation_path_mentions_logto_admin() {
        let forbidden_host_token = format!("{}-{}", "logto", "admin");
        for &op in ALL_OPERATIONS {
            let s = spec(op);
            assert!(!s.path.to_ascii_lowercase().contains(&forbidden_host_token));
            assert!(!s.id.to_ascii_lowercase().contains("admin_endpoint"));
            for field in s
                .path_params
                .iter()
                .chain(s.query_fields.iter())
                .chain(s.body_fields.iter())
            {
                let lower = field.to_ascii_lowercase();
                assert_ne!(lower, "authorization");
                assert_ne!(lower, "redirecturi");
                assert_ne!(lower, "url");
            }
        }
    }

    #[test]
    fn servers_list_query_matches_backend() {
        let s = spec(Operation::ServersList);
        assert_eq!(
            s.query_fields,
            &[
                "page",
                "page_size",
                "name",
                "ip",
                "ssh_user",
                "description",
                "group_name",
                "q",
                "sort",
                "host_key_status",
            ]
        );
    }
}
