// @generated by scripts/generate-operations.mjs — DO NOT EDIT BY HAND
// source: contracts/desktop-operations.json
// content-hash: 79b0f89db58d0bc1
// regenerate: npm run contracts:generate
//
// IPC-callable operations only: availability=available && invocation=ipc_via_rust.
// React may pass these ids to cloud_call; native_only / blocked ops are excluded.

/** Sorted, frozen allowlist of WebView/business IPC operation ids. */
export const IPC_CALLABLE_OPERATION_IDS = Object.freeze([
  "account.telegram.bindStart",
  "account.telegram.bindStatus",
  "account.telegram.unbind",
  "auth.me",
  "monitoring.applications.get",
  "monitoring.applications.list",
  "monitoring.foundation.get",
  "monitoring.foundation.list",
  "monitoring.patrolRecords.get",
  "monitoring.patrolRecords.list",
  "monitoring.patrolRounds.get",
  "monitoring.patrolRounds.list",
  "monitoring.patrolTasks.get",
  "monitoring.patrolTasks.list",
  "problems.getConvergenceTimeline",
  "problems.list",
  "remediation.get",
  "remediation.list",
  "servers.get",
  "servers.list",
  "subscription.ai.get",
  "subscription.entitlements.current",
] as const);

/** Union of contract operation ids that React may request via cloud_call. */
export type IpcCallableOperationId = (typeof IPC_CALLABLE_OPERATION_IDS)[number];
