// @generated by apps/desktop/scripts/generate-desktop-routes.mjs
// DO NOT EDIT — regenerate with: node apps/desktop/scripts/generate-desktop-routes.mjs
// Source: apps/desktop/contracts/desktop-api-routes.json (version 1)

//! Desktop cloud API route allowlist (generated).
//!
//! Matching rules (keep in sync with TypeScript `generated-api-routes.ts`):
//! - relative `/api/` path only
//! - no backslash, no fragment
//! - query parsed separately (stripped before match)
//! - no encoded slash/backslash/dot segment
//! - no encoded percent (%25) / controls (%00-%1f, %7f) in path
//! - no empty / `.` / `..` segments
//! - blocked paths checked before prefix families

#![allow(dead_code)]

/// One allowlisted path-prefix family and its HTTP methods.
#[derive(Debug, Clone, Copy)]
pub struct RouteFamily {
    pub prefix: &'static str,
    pub methods: &'static [&'static str],
}

/// Version of the route catalog contract.
pub const CATALOG_VERSION: u32 = 1;

/// Allowlisted route families (prefix + methods).
pub static FAMILIES: &[RouteFamily] = &[
    RouteFamily {
        prefix: "/api/dashboard/overview",
        methods: &["GET"],
    },
    RouteFamily {
        prefix: "/api/auth/me",
        methods: &["GET", "POST", "DELETE"],
    },
    RouteFamily {
        prefix: "/api/auth/telegram-widget",
        methods: &["GET"],
    },
    RouteFamily {
        prefix: "/api/auth/ws-token",
        methods: &["POST"],
    },
    RouteFamily {
        prefix: "/api/entitlements/current",
        methods: &["GET"],
    },
    RouteFamily {
        prefix: "/api/subscription/ai",
        methods: &["GET", "POST"],
    },
    RouteFamily {
        prefix: "/api/servers",
        methods: &["GET", "POST", "PATCH", "DELETE"],
    },
    RouteFamily {
        prefix: "/api/security/credentials",
        methods: &["GET", "POST", "PATCH", "DELETE"],
    },
    RouteFamily {
        prefix: "/api/monitoring",
        methods: &["GET", "POST", "PATCH", "DELETE"],
    },
    RouteFamily {
        prefix: "/api/problems",
        methods: &["GET", "POST"],
    },
    RouteFamily {
        prefix: "/api/oncall/remediation-queue",
        methods: &["GET", "POST"],
    },
    RouteFamily {
        prefix: "/api/incident-reports",
        methods: &["GET", "POST"],
    },
];

/// Explicitly blocked paths (checked before family prefixes).
pub static BLOCKED: &[&str] = &[
    "/api/auth/logto/config",
    "/api/auth/logto/exchange",
    "/api/auth/login",
    "/api/auth/refresh",
];

/// Return true when `method` + `path_with_query` is allowlisted for desktop cloud proxy.
pub fn match_request(method: &str, path_with_query: &str) -> bool {
    let Some(path) = normalize_path(path_with_query) else {
        return false;
    };
    // Blocked before prefix families.
    if BLOCKED.contains(&path) {
        return false;
    }
    let method_upper = method.to_ascii_uppercase();
    for family in FAMILIES {
        if path_matches_prefix(path, family.prefix)
            && family
                .methods
                .iter()
                .any(|m| m.eq_ignore_ascii_case(&method_upper))
        {
            return true;
        }
    }
    false
}

fn path_matches_prefix(path: &str, prefix: &str) -> bool {
    path == prefix || path.starts_with(&format!("{prefix}/"))
}

/// Normalize a request path for allowlist matching.
///
/// Returns `None` when the input is not a safe relative `/api/` path.
fn normalize_path(path_with_query: &str) -> Option<&str> {
    if path_with_query.is_empty() {
        return None;
    }
    // No backslash (Windows path smuggling) and no fragment.
    if path_with_query.contains('\\') || path_with_query.contains('#') {
        return None;
    }
    // Absolute or protocol-relative URLs are rejected.
    if path_with_query.contains("://") || path_with_query.starts_with("//") {
        return None;
    }
    if !path_with_query.starts_with('/') {
        return None;
    }

    // Query is parsed separately — strip for path match.
    let path = match path_with_query.split_once('?') {
        Some((p, _)) => p,
        None => path_with_query,
    };

    // Must be under /api/ (not merely /api).
    if !path.starts_with("/api/") {
        return None;
    }

    // Reject forbidden percent-encodings in the path only (query already stripped).
    // Blocks: %2e/%2f/%5c, encoded percent %25 (double-encoding), controls %00-%1f/%7f.
    if path_has_forbidden_percent_encoding(path) {
        return None;
    }

    // Segment checks: no empty, no "." / "..".
    // path always starts with '/' so split yields a leading empty str.
    for segment in path.split('/').skip(1) {
        if segment.is_empty() || segment == "." || segment == ".." {
            return None;
        }
    }

    Some(path)
}

/// True when path contains a percent-encoding that is unsafe for allowlist matching.
fn path_has_forbidden_percent_encoding(path: &str) -> bool {
    let bytes = path.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] != b'%' {
            i += 1;
            continue;
        }
        // Incomplete or non-hex percent sequence is rejected.
        if i + 2 >= bytes.len() {
            return true;
        }
        let h1 = bytes[i + 1];
        let h2 = bytes[i + 2];
        let Some(v) = hex_byte(h1, h2) else {
            return true;
        };
        // Encoded controls, DEL, percent (double-encoding), dot, slash, backslash.
        if v <= 0x1f || v == 0x7f || v == 0x25 || v == 0x2e || v == 0x2f || v == 0x5c {
            return true;
        }
        i += 3;
    }
    false
}

fn hex_byte(h1: u8, h2: u8) -> Option<u8> {
    let n1 = hex_nibble(h1)?;
    let n2 = hex_nibble(h2)?;
    Some((n1 << 4) | n2)
}

fn hex_nibble(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

#[cfg(test)]
mod generated_unit_tests {
    use super::*;

    #[test]
    fn catalog_version_is_one() {
        assert_eq!(CATALOG_VERSION, 1);
    }

    #[test]
    fn blocked_before_any_prefix() {
        // Even if a blocked path looked like a family descendant, blocked wins.
        assert!(!match_request("GET", "/api/auth/login"));
        assert!(!match_request("POST", "/api/auth/refresh"));
    }
}
