// @generated by apps/desktop/scripts/generate-desktop-routes.mjs
// DO NOT EDIT — regenerate with: node apps/desktop/scripts/generate-desktop-routes.mjs
// Source: apps/desktop/contracts/desktop-api-routes.json (version 1)

/**
 * Desktop cloud API route allowlist (generated).
 *
 * Matching rules (keep in sync with Rust `cloud_proxy/routes.rs`):
 * - relative `/api/` path only
 * - no backslash, no fragment
 * - query parsed separately (stripped before match)
 * - no encoded slash/backslash/dot segment
 * - no encoded percent (%25) / controls (%00-%1f, %7f) in path
 * - no empty / `.` / `..` segments
 * - blocked paths checked before prefix families
 */

export const CATALOG_VERSION = 1 as const;

export type RouteFamily = {
  readonly prefix: string;
  readonly methods: readonly string[];
};

export const FAMILIES: readonly RouteFamily[] = [
  { prefix: "/api/dashboard/overview", methods: ["GET"] as const },
  { prefix: "/api/auth/me", methods: ["GET", "POST", "DELETE"] as const },
  { prefix: "/api/auth/telegram-widget", methods: ["GET"] as const },
  { prefix: "/api/auth/ws-token", methods: ["POST"] as const },
  { prefix: "/api/subscription/ai", methods: ["GET", "POST"] as const },
  { prefix: "/api/servers", methods: ["GET", "POST", "PATCH", "DELETE"] as const },
  { prefix: "/api/security/credentials", methods: ["GET", "POST", "PATCH", "DELETE"] as const },
  { prefix: "/api/monitoring", methods: ["GET", "POST", "PATCH", "DELETE"] as const },
  { prefix: "/api/problems", methods: ["GET", "POST"] as const },
  { prefix: "/api/oncall/remediation-queue", methods: ["GET", "POST"] as const },
  { prefix: "/api/incident-reports", methods: ["GET", "POST"] as const }
];

export const BLOCKED: readonly string[] = [
  "/api/auth/logto/config",
  "/api/auth/logto/exchange",
  "/api/auth/login",
  "/api/auth/refresh"
];

/**
 * Return true when `method` + `pathWithQuery` is allowlisted for desktop cloud proxy.
 */
export function isDesktopApiRequestAllowed(method: string, pathWithQuery: string): boolean {
  const path = normalizePath(pathWithQuery);
  if (path === null) {
    return false;
  }
  // Blocked before prefix families.
  if (BLOCKED.includes(path)) {
    return false;
  }
  const methodUpper = method.toUpperCase();
  for (const family of FAMILIES) {
    if (pathMatchesPrefix(path, family.prefix) && family.methods.includes(methodUpper)) {
      return true;
    }
  }
  return false;
}

function pathMatchesPrefix(path: string, prefix: string): boolean {
  return path === prefix || path.startsWith(prefix + "/");
}

/**
 * Normalize a request path for allowlist matching.
 * Returns null when the input is not a safe relative `/api/` path.
 */
function normalizePath(pathWithQuery: string): string | null {
  if (!pathWithQuery) {
    return null;
  }
  // No backslash (Windows path smuggling) and no fragment.
  if (pathWithQuery.includes("\\") || pathWithQuery.includes("#")) {
    return null;
  }
  // Absolute or protocol-relative URLs are rejected.
  if (pathWithQuery.includes("://") || pathWithQuery.startsWith("//")) {
    return null;
  }
  if (!pathWithQuery.startsWith("/")) {
    return null;
  }

  // Query is parsed separately — strip for path match.
  const q = pathWithQuery.indexOf("?");
  const path = q === -1 ? pathWithQuery : pathWithQuery.slice(0, q);

  // Must be under /api/ (not merely /api).
  if (!path.startsWith("/api/")) {
    return null;
  }

  // Reject forbidden percent-encodings in the path only (query already stripped).
  // Blocks: %2e/%2f/%5c, encoded percent %25 (double-encoding), controls %00-%1f/%7f.
  if (pathHasForbiddenPercentEncoding(path)) {
    return null;
  }

  // Segment checks: no empty, no "." / "..".
  // path always starts with '/' so split yields a leading empty str.
  const segments = path.split("/");
  for (let i = 1; i < segments.length; i++) {
    const segment = segments[i];
    if (segment === "" || segment === "." || segment === "..") {
      return null;
    }
  }

  return path;
}

/** True when path contains a percent-encoding that is unsafe for allowlist matching. */
function pathHasForbiddenPercentEncoding(path: string): boolean {
  for (let i = 0; i < path.length; i++) {
    if (path.charCodeAt(i) !== 0x25 /* % */) {
      continue;
    }
    // Incomplete or non-hex percent sequence is rejected.
    if (i + 2 >= path.length) {
      return true;
    }
    const v = hexByte(path.charCodeAt(i + 1), path.charCodeAt(i + 2));
    if (v === null) {
      return true;
    }
    // Encoded controls, DEL, percent (double-encoding), dot, slash, backslash.
    if (v <= 0x1f || v === 0x7f || v === 0x25 || v === 0x2e || v === 0x2f || v === 0x5c) {
      return true;
    }
    i += 2; // loop will +1
  }
  return false;
}

function hexByte(h1: number, h2: number): number | null {
  const n1 = hexNibble(h1);
  const n2 = hexNibble(h2);
  if (n1 === null || n2 === null) {
    return null;
  }
  return (n1 << 4) | n2;
}

function hexNibble(b: number): number | null {
  if (b >= 0x30 && b <= 0x39) return b - 0x30; // 0-9
  if (b >= 0x61 && b <= 0x66) return b - 0x61 + 10; // a-f
  if (b >= 0x41 && b <= 0x46) return b - 0x41 + 10; // A-F
  return null;
}
